# Generated by Django 3.1.5 on 2021-01-14 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Research', '0002_projects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': '横向项目管理'},
        ),
        migrations.AlterModelOptions(
            name='researcharticles',
            options={'ordering': ('-Rpublish',), 'verbose_name_plural': '论文管理'},
        ),
        migrations.AlterField(
            model_name='projects',
            name='accomplish',
            field=models.CharField(max_length=100, verbose_name='项目完成情况'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='charge_dept',
            field=models.CharField(max_length=50, verbose_name='负责人院别'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='charge_man',
            field=models.CharField(max_length=30, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='check_date',
            field=models.DateTimeField(verbose_name='鉴定日期'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='contract_funds',
            field=models.IntegerField(verbose_name='合同经费(元）'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='contract_id',
            field=models.IntegerField(verbose_name='合同序号'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='delegated_dept',
            field=models.CharField(max_length=50, verbose_name='委托单位'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='endpoint',
            field=models.DateTimeField(auto_now=True, verbose_name='结题时间'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='equip_funds',
            field=models.IntegerField(verbose_name='设备经费（元)'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='money_in_1',
            field=models.IntegerField(verbose_name='到账金额1（元)'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='money_in_2',
            field=models.IntegerField(verbose_name='到账金额2(元)'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='money_in_3',
            field=models.IntegerField(verbose_name='到账金额3(元)'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='money_in_4',
            field=models.IntegerField(verbose_name='到账金额4(元)'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='money_in_all',
            field=models.IntegerField(verbose_name='总到账金额(元)'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='money_in_date_1',
            field=models.DateTimeField(auto_now=True, verbose_name='到款日期'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='money_in_date_2',
            field=models.DateTimeField(auto_now=True, verbose_name='到款日期'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='money_in_date_3',
            field=models.DateTimeField(auto_now=True, verbose_name='到款日期'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='money_in_date_4',
            field=models.DateTimeField(auto_now=True, verbose_name='到款日期'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='participator_1',
            field=models.CharField(max_length=30, verbose_name='参与者1'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='participator_10',
            field=models.CharField(default='无', max_length=30, verbose_name='参与者10'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='participator_2',
            field=models.CharField(default='无', max_length=30, verbose_name='参与者2'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='participator_3',
            field=models.CharField(default='无', max_length=30, verbose_name='参与者3'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='participator_4',
            field=models.CharField(default='无', max_length=30, verbose_name='参与者4'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='participator_5',
            field=models.CharField(default='无', max_length=30, verbose_name='参与者5'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='participator_6',
            field=models.CharField(default='无', max_length=30, verbose_name='参与者6'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='participator_7',
            field=models.CharField(default='无', max_length=30, verbose_name='参与者7'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='participator_8',
            field=models.CharField(default='无', max_length=30, verbose_name='参与者8'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='participator_9',
            field=models.CharField(default='无', max_length=30, verbose_name='参与者9'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='proj_id',
            field=models.IntegerField(verbose_name='项目序号'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='proj_intro',
            field=models.TextField(max_length=100, verbose_name='项目简介'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='proj_name',
            field=models.TextField(max_length=50, verbose_name='项目名'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='proj_type',
            field=models.CharField(max_length=30, verbose_name='项目类型'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_time',
            field=models.DateTimeField(verbose_name='立项时间'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='valid_time',
            field=models.IntegerField(verbose_name='有效期限(天）'),
        ),
        migrations.AlterField(
            model_name='researcharticles',
            name='Rauthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='researcharticles',
            name='Rcategory',
            field=models.CharField(max_length=100, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='researcharticles',
            name='Rfund',
            field=models.IntegerField(default=0, verbose_name='研究经费(元)'),
        ),
        migrations.AlterField(
            model_name='researcharticles',
            name='Rinstitution',
            field=models.CharField(max_length=100, verbose_name='所属机构'),
        ),
        migrations.AlterField(
            model_name='researcharticles',
            name='Rintroduction',
            field=models.TextField(verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='researcharticles',
            name='Rjournal',
            field=models.CharField(max_length=100, verbose_name='来源期刊'),
        ),
        migrations.AlterField(
            model_name='researcharticles',
            name='Rpublish',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发文时间'),
        ),
        migrations.AlterField(
            model_name='researcharticles',
            name='Rrank',
            field=models.CharField(max_length=100, verbose_name='检索分类'),
        ),
        migrations.AlterField(
            model_name='researcharticles',
            name='Rtitle',
            field=models.TextField(max_length=100, verbose_name='论文名称'),
        ),
    ]
