# Generated by Django 3.1.5 on 2021-01-15 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Research', '0003_auto_20210114_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcharticles',
            name='Rauthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Article', to=settings.AUTH_USER_MODEL, verbose_name='第一作者'),
        ),
        migrations.AlterField(
            model_name='researcharticles',
            name='Rpublish',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发表时间'),
        ),
    ]
